version: '3.8'

services:
  backend:
    build: .
    container_name: go_server
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Lưu ý: DB_HOST phải trùng với container_name ở file kia
      - DB_HOST=postgres_db 
      - DB_USER=admin
      - DB_PASSWORD=MatKhauSieuManh123
      - DB_NAME=app_db
      - DB_PORT=5432
    mem_limit: 150m
    networks:
      - app_network  # <--- Gắn vào cùng mạng với DB

networks:
  app_network:
    external: true   # <--- Dùng chung mạng
